import { Category } from 'types';

export const dummyProducts = [
  {
    name: "Men's Casual T-Shirt",
    category: Category.Men,
    description: 'A comfortable and stylish casual t-shirt for everyday wear.',
    images: ['https://example.com/images/tshirt1.jpg'],
    price: 19.99,
    rating: 4.5,
    stock: { S: 20, M: 50, L: 30 },
    comingSoon: false,
    brand: 'Brand A',
    size: ['S', 'M', 'L'],
  },
  {
    name: "Women's Summer Dress",
    category: Category.Women,
    description: 'A light and breezy summer dress perfect for warm weather.',
    images: ['https://example.com/images/dress1.jpg'],
    price: 29.99,
    rating: 4.7,
    stock: { M: 15, L: 25 },
    comingSoon: false,
    brand: 'Brand B',
    size: ['M', 'L'],
  },
  {
    name: "Men's Denim Jacket",
    category: Category.Men,
    description: 'A classic denim jacket that never goes out of style.',
    images: ['https://example.com/images/jacket1.jpg'],
    price: 49.99,
    rating: 4.2,
    stock: { S: 10, M: 5, L: 20, XL: 8 },
    comingSoon: false,
    brand: 'Brand C',
    size: ['S', 'M', 'L', 'XL'],
  },
  {
    name: "Kids' Cotton T-Shirt",
    category: Category.Kids,
    description: 'Soft cotton t-shirt for kids.',
    images: ['https://example.com/images/kidstshirt1.jpg'],
    price: 14.99,
    rating: 4.6,
    stock: { S: 30, M: 25 },
    comingSoon: false,
    brand: 'Brand Y',
    size: ['S', 'M'],
  },
  {
    name: "Kids' Sneakers",
    category: Category.Kids,
    description: 'Comfortable sneakers for active kids.',
    images: ['https://example.com/images/kidssneakers1.jpg'],
    price: 39.99,
    rating: 4.5,
    stock: { S: 15, M: 20 },
    comingSoon: false,
    brand: 'Brand Z',
    size: ['S', 'M'],
  },
  {
    name: "Kids' Hoodie",
    category: Category.Kids,
    description: 'Warm and cozy hoodie for kids.',
    images: ['https://example.com/images/kidshoodie1.jpg'],
    price: 29.99,
    rating: 4.7,
    stock: { S: 20, M: 15 },
    comingSoon: false,
    brand: 'Brand AA',
    size: ['S', 'M'],
  },
  {
    name: "Women's Handbag",
    category: Category.Women,
    description: 'A stylish handbag for everyday use.',
    images: ['https://example.com/images/handbag1.jpg'],
    price: 89.99,
    rating: 4.3,
    stock: { OneSize: 5 },
    comingSoon: false,
    brand: 'Brand F',
    size: ['OneSize'],
  },
  {
    name: "Men's Formal Shirt",
    category: Category.Men,
    description: 'A classic formal shirt for business or special occasions.',
    images: ['https://example.com/images/formalshirt1.jpg'],
    price: 34.99,
    rating: 4.4,
    stock: { M: 20, L: 10 },
    comingSoon: false,
    brand: 'Brand G',
    size: ['M', 'L'],
  },
  {
    name: "Women's Blouse",
    category: Category.Women,
    description: 'A stylish blouse for work or casual outings.',
    images: ['https://example.com/images/blouse1.jpg'],
    price: 39.99,
    rating: 4.6,
    stock: { S: 15, M: 20 },
    comingSoon: false,
    brand: 'Brand H',
    size: ['S', 'M'],
  },
  {
    name: "Men's Running Shoes",
    category: Category.Men,
    description:
      'Lightweight running shoes designed for comfort and performance.',
    images: ['https://example.com/images/shoes1.jpg'],
    price: 59.99,
    rating: 4.6,
    stock: { M: 15, L: 10 },
    comingSoon: false,
    brand: 'Brand E',
    size: ['M', 'L'],
  },
];
