export const dummyProducts = [
  {
    name: "Men's Casual T-Shirt",
    description: 'A comfortable and stylish casual t-shirt for everyday wear.',
    images: ['https://example.com/images/tshirt1.jpg'],
    price: 19.99,
    rating: 4.5,
    stock: {
      S: 20,
      M: 50,
      L: 30,
    },
    comingSoon: false,
    brand: 'Brand A',
    size: ['S', 'M', 'L'],
  },
  {
    name: "Women's Summer Dress",
    description: 'A light and breezy summer dress perfect for warm weather.',
    images: ['https://example.com/images/dress1.jpg'],
    price: 29.99,
    rating: 4.7,
    stock: {
      M: 15,
      L: 25,
    },
    comingSoon: false,
    brand: 'Brand B',
    size: ['M', 'L'],
  },
  {
    name: "Men's Denim Jacket",
    description: 'A classic denim jacket that never goes out of style.',
    images: ['https://example.com/images/jacket1.jpg'],
    price: 49.99,
    rating: 4.2,
    stock: {
      S: 10,
      M: 5,
      L: 20,
      XL: 8,
    },
    comingSoon: false,
    brand: 'Brand C',
    size: ['S', 'M', 'L', 'XL'],
  },
  {
    name: "Women's Yoga Pants",
    description: 'Comfortable yoga pants for workouts or lounging.',
    images: ['https://example.com/images/yogapants1.jpg'],
    price: 39.99,
    rating: 4.8,
    stock: {
      S: 30,
      M: 25,
    },
    comingSoon: false,
    brand: 'Brand D',
    size: ['S', 'M'],
  },
  {
    name: "Men's Running Shoes",
    description:
      'Lightweight running shoes designed for comfort and performance.',
    images: ['https://example.com/images/shoes1.jpg'],
    price: 59.99,
    rating: 4.6,
    stock: {
      M: 15,
      L: 10,
    },
    comingSoon: false,
    brand: 'Brand E',
    size: ['M', 'L'],
  },
  {
    name: "Women's Handbag",
    description: 'A stylish handbag for everyday use.',
    images: ['https://example.com/images/handbag1.jpg'],
    price: 89.99,
    rating: 4.3,
    stock: {
      OneSize: 5,
    },
    comingSoon: false,
    brand: 'Brand F',
    size: ['OneSize'],
  },
  {
    name: "Men's Formal Shirt",
    description: 'A classic formal shirt for business or special occasions.',
    images: ['https://example.com/images/shirt1.jpg'],
    price: 34.99,
    rating: 4.1,
    stock: {
      M: 40,
      L: 20,
    },
    comingSoon: false,
    brand: 'Brand G',
    size: ['M', 'L'],
  },
  {
    name: "Women's Winter Coat",
    description: 'A warm and stylish winter coat for cold weather.',
    images: ['https://example.com/images/coat1.jpg'],
    price: 99.99,
    rating: 4.9,
    stock: {
      S: 5,
      M: 10,
      L: 3,
    },
    comingSoon: false,
    brand: 'Brand H',
    size: ['S', 'M', 'L'],
  },
  {
    name: "Men's Swim Trunks",
    description: 'Comfortable swim trunks for beach or pool.',
    images: ['https://example.com/images/swimtrunks1.jpg'],
    price: 24.99,
    rating: 4.4,
    stock: {
      M: 20,
      L: 15,
    },
    comingSoon: false,
    brand: 'Brand I',
    size: ['M', 'L'],
  },
  {
    name: "Women's Athletic Sneakers",
    description:
      'Stylish and comfortable sneakers for workouts and casual outings.',
    images: ['https://example.com/images/sneakers1.jpg'],
    price: 69.99,
    rating: 4.5,
    stock: {
      S: 10,
      M: 20,
      L: 15,
    },
    comingSoon: false,
    brand: 'Brand J',
    size: ['S', 'M', 'L'],
  },
  {
    name: "Men's Cargo Shorts",
    description: 'Durable cargo shorts with multiple pockets for convenience.',
    images: ['https://example.com/images/shorts1.jpg'],
    price: 34.99,
    rating: 4.3,
    stock: {
      M: 25,
      L: 30,
    },
    comingSoon: false,
    brand: 'Brand K',
    size: ['M', 'L'],
  },
  {
    name: "Women's Blouse",
    description: 'A chic blouse suitable for both work and casual outings.',
    images: ['https://example.com/images/blouse1.jpg'],
    price: 39.99,
    rating: 4.6,
    stock: {
      S: 15,
      M: 20,
    },
    comingSoon: false,
    brand: 'Brand L',
    size: ['S', 'M'],
  },
  {
    name: "Men's Leather Belt",
    description: 'A classic leather belt that complements any outfit.',
    images: ['https://example.com/images/belt1.jpg'],
    price: 24.99,
    rating: 4.2,
    stock: {
      OneSize: 50,
    },
    comingSoon: false,
    brand: 'Brand M',
    size: ['OneSize'],
  },
  {
    name: "Women's Sunglasses",
    description: 'Stylish sunglasses to protect your eyes from the sun.',
    images: ['https://example.com/images/sunglasses1.jpg'],
    price: 49.99,
    rating: 4.8,
    stock: {
      OneSize: 30,
    },
    comingSoon: false,
    brand: 'Brand N',
    size: ['OneSize'],
  },
  {
    name: "Men's Sports Watch",
    description: 'A durable sports watch with multiple features.',
    images: ['https://example.com/images/watch1.jpg'],
    price: 89.99,
    rating: 4.4,
    stock: {
      OneSize: 20,
    },
    comingSoon: false,
    brand: 'Brand O',
    size: ['OneSize'],
  },
  {
    name: "Women's Scarf",
    description: 'A fashionable scarf to add style to any outfit.',
    images: ['https://example.com/images/scarf1.jpg'],
    price: 19.99,
    rating: 4.5,
    stock: {
      OneSize: 40,
    },
    comingSoon: false,
    brand: 'Brand P',
    size: ['OneSize'],
  },
  {
    name: "Men's Casual Sneakers",
    description: 'Comfortable sneakers for everyday wear.',
    images: ['https://example.com/images/casualsneakers1.jpg'],
    price: 54.99,
    rating: 4.6,
    stock: {
      M: 15,
      L: 10,
    },
    comingSoon: false,
    brand: 'Brand Q',
    size: ['M', 'L'],
  },
  {
    name: "Women's Flip Flops",
    description: 'Lightweight flip flops for summer outings.',
    images: ['https://example.com/images/flipflops1.jpg'],
    price: 14.99,
    rating: 4.3,
    stock: {
      S: 25,
      M: 30,
    },
    comingSoon: false,
    brand: 'Brand R',
    size: ['S', 'M'],
  },
  {
    name: "Men's Beanie",
    description: 'A warm beanie for cold weather.',
    images: ['https://example.com/images/beanie1.jpg'],
    price: 19.99,
    rating: 4.5,
    stock: {
      OneSize: 50,
    },
    'coming Soon': false,
    brand: 'Brand S',
    size: ['OneSize'],
  },
  {
    name: "Women's Tote Bag",
    description: 'A spacious tote bag for daily essentials.',
    images: ['https://example.com/images/totebag1.jpg'],
    price: 39.99,
    rating: 4.4,
    stock: {
      OneSize: 20,
    },
    comingSoon: false,
    brand: 'Brand T',
    size: ['OneSize'],
  },
  {
    name: "Men's Athletic Shorts",
    description: 'Breathable athletic shorts for workouts.',
    images: ['https://example.com/images/athleticshorts1.jpg'],
    price: 29.99,
    rating: 4.6,
    stock: {
      M: 25,
      L: 20,
    },
    comingSoon: false,
    brand: 'Brand U',
    size: ['M', 'L'],
  },
  {
    name: "Women's Cardigan",
    description: 'A cozy cardigan for layering.',
    images: ['https://example.com/images/cardigan1.jpg'],
    price: 49.99,
    rating: 4.7,
    stock: {
      S: 10,
      M: 15,
      L: 5,
    },
    comingSoon: false,
    brand: 'Brand V',
    size: ['S', 'M', 'L'],
  },
  {
    name: "Men's Graphic Tee",
    description: 'A trendy graphic tee for casual outings.',
    images: ['https://example.com/images/graphictee1.jpg'],
    price: 24.99,
    rating: 4.3,
    stock: {
      M: 30,
      L: 25,
    },
    comingSoon: false,
    brand: 'Brand W',
    size: ['M', 'L'],
  },
  {
    name: "Women's Ankle Boots",
    description: 'Stylish ankle boots for a chic look.',
    images: ['https://example.com/images/ankleboots1.jpg'],
    price: 79.99,
    rating: 4.8,
    stock: {
      S: 5,
      M: 10,
      L: 8,
    },
    comingSoon: false,
    brand: 'Brand X',
    size: ['S', 'M', 'L'],
  },
];
